<?php
/**
 * @file
 *
 * Defines a custom field for constructing a custom poutine.
 */

require_once('poutine_maker.fillings.inc');

/**
 * Implements hook_field_info().
 */
function poutine_maker_field_info() {
  return array(
    'poutine_maker_poutine_maker' => array(
      'label' => t('Custom Poutine'),
      'description' => t('Custom Poutine Field'),
      'default_widget' => 'poutine_maker_poutine_maker_in',
      'default_formatter' => 'poutine_maker_poutine_maker_out',
    ),
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function poutine_maker_field_formatter_info() {
  return array(
    'poutine_maker_poutine_maker_out' => array(
      'label' => t('Default'),
      'field types' => array('poutine_maker_poutine_maker'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function poutine_maker_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  foreach ($items as $delta => $item) {
    $element[$delta] = poutine_maker_format_field($item);
  }
  return $element;
}

/**
 * Helper to render a single formatted entry
 */
function poutine_maker_format_field($item) {
  $element = array();
  $element = array(
    '#type' => 'container',
    '#attributes' => array( 'class' => array( 'field-item') ),
    'text' => array(
      '#markup' => 'poutine_maker rendering not implemented',
    ),
  );
  return $element;
}

/**
 * Implements hook_field_widget_info().
 */
function poutine_maker_field_widget_info() {
  return array(
    'poutine_maker_poutine_maker_in' => array(
      'label' => t('Default'),
      'field types' => array('poutine_maker_poutine_maker'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function poutine_maker_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $field_name = $instance['field_name'];
  $fieldset_info = element_info('fieldset');
  $process = array_merge($fieldset_info['#process'], array('poutine_maker_ignore_parent'));

  $item =& $items[$delta];
  $element += array(
    '#title' => t('Phone Number'),
    '#type' => 'fieldset',
    '#delta' => $delta,
  );
  $element['name'] = array(
    '#title' => t('Name'),
    '#type' => 'textfield',
    '#default_value' => isset($item['name']) ? $item['name'] : '',
  );
  $element['vegetarian'] = array(
    '#title' => t('Vegetarian'),
    '#type' => 'checkbox',
    '#default_value' => isset($item['vegetarian']) ? $item['vegetarian'] : '',
  );
  $element['fillings'] = array(
    '#title' => t('Fillings'),
    '#type' => 'fieldset',
    '#process' => $process,
  );
  foreach (poutine_maker_fillings('all') as $filling) {
    $filling_machine = strtolower($filling);
    $element['fillings'][$filling_machine] = array(
      '#title' => t($filling),
      '#type' => 'checkbox',
      '#default_value' => isset($item[$filling_machine]) ? $item[$filling_machine] : '',
    );
  }
  foreach (poutine_maker_fillings('meat') as $nonvegetarian_filling) {
    $filling_machine = strtolower($nonvegetarian_filling);
    $element['fillings'][$filling_machine]['#states'] = array(
      'visible' => array(
        _poutine_maker_make_jquery_selector($field_name, $langcode, $delta, 'vegetarian') =>
          array('checked' => FALSE),
      ),
    );
  }
  return $element;
}

function _poutine_maker_make_jquery_selector($field_name, $langcode, $delta, $item_name) {
  return ':input[name="' . $field_name . '[' . $langcode . '][' . $delta . '][' . $item_name . ']"], ' .
    ':input[name$="[' . $field_name . '][' . $langcode . '][' . $delta . '][' . $item_name . ']"]';
}

/**
 * Process callback to remove one level of parentage
 */
function poutine_maker_ignore_parent(&$form, &$form_state, $complete) {
  array_pop($form['#parents']);
  return $form;
}

/**
 * Implements hook_field_is_empty().
 */
function poutine_maker_field_is_empty($item, $field) {
  return FALSE;
}

/**
 * Implements hook_field_validate().
 */
function poutine_maker_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  $title = "<strong>{$instance['label']}</strong>";

  foreach ($items as $delta => $item) {
    /*
    $errors[$field['field_name']][$langcode][$delta][] = array(
      'error' => 'poutine_maker_invalid_full',
      'message' => t($title . ': Your poutine is invalid.'),
    );
     */
  }
}

/**
 * Implements hook_field_widget_error().
 */
function poutine_maker_field_widget_error($element, $error, $form, &$form_state) {
  switch($error['error']) {
  case 'poutine_maker_invalid_full':
    form_error($element, $error['message']);
    break;
  }
}
